### PR TITLE
Python 3.6 support for stashcp

### PR DESCRIPTION
**Pull request by matyasselmeci**
Syntax fixes, standard library rearrangement, and string handling. Tested on a local CentOS 8 VM and a Fermicloud SLF 7 VM.

### CODE REVIEW

**Comment by djw8605** [comment]
Could you also add Python 3 to the .travis.yml test matrix, otherwise, this looks good. (though, a lot of the tests happen within a docker container)

**Comment by djw8605** [comment]
What's up with the revert?

**Comment by matyasselmeci** [comment]
That commit doesn't actually do anything useful -- it adds python 3.6 to the build matrix _outside_ docker but has no effect on what runs inside the docker images.

I'll squash/drop those once I have something working.

**Comment by matyasselmeci** [comment]
I fixed the CI so there are a couple new test runs that use Python 3 instead of 2. @djw8605 , can you take a look?

**Pull request merged**
