### PR TITLE
timeout to 5 mins

### PR DESCRIPTION
**Pull request by tony044**
Ilija and Rob asked to have the limit be 5 minutes

### CODE REVIEW

**Comment by djw8605** [comment]
This looks good.  Should this go into v3.4?

**Comment by tony044** [comment]
Just saw this - is it too late to incorporate in v3.3?

**Comment by djw8605** [comment]
Yeah, v3.3 has already been tagged.

-Derek

**Comment by tony044** [comment]
Ok, can we just make a v3.4 then?

**Comment by djw8605** [comment]
Done, v3.4 tagged.

-Derek

**Comment by tony044** [comment]
Last thing - could you also push/publish the tag? I don't think I have permission to do it. After cloning, doing "git tag -l" only shows up to v3.1 for some reason.

**Comment by djw8605** [comment]
Yup, ok.  I pushed all of the tags.  I forgot to push them to this repo.

**Comment by tony044** [comment]
Super, thanks

**Pull request merged**
