### PR TITLE
K8s caches

### PR DESCRIPTION
**Pull request by efajardo**
Pull request to add the K8s Caches

### CODE REVIEW

**Comment by efajardo** [comment]
@djw8605 I am holding on this one till we do the merging of the caches.

**Comment by efajardo** [comment]
@djw8605 this somehow got lost. I updated the yaml file too.

**Comment by efajardo** [comment]
@djw8605 this is ready for review whenever you have time.

**Comment by djw8605** [comment]
For the jobs, it seems the kansas city cache isn't working:
https://travis-ci.org/opensciencegrid/StashCache/jobs/500469973

Both xrootd and HTTP is failing.

**Comment by djw8605** [comment]
For example, https://travis-ci.org/opensciencegrid/StashCache/jobs/500469973#L1781

**Comment by efajardo** [comment]
YEa the node went booted up in the wrong kernel last night and we have not been able to bring it back.

**Pull request merged**
