### PR TITLE
stashcp in Python 

### PR DESCRIPTION
**Pull request by tony044**
Located in stashcp2 directory. Hope this works

### CODE REVIEW

**Comment by djw8605** [comment]
There are still a ton of commits.

Can you just start on a clean repo.  Copy in your stashcp2 stuff, and commit it.  We will lose the commit history of the new stashcp, but at least it will be a much cleaner commit.

**Comment by tony044** [comment]
So delete my fork of StashCache and then re-fork and copy in the new files?

**Comment by djw8605** [comment]
Nah, you don't have to delete the fork.  Just on your local machine, do this:

1. Clone the OSG StashCache repo in a different directory, so it's clean.
2. Make a new branch, say, add_stashcp2
3. Copy in the new files that you made.
4. Add your repo as a new remote:

    ```
    $ git remote add tony https://github.com/tony044/StashCache-Tony.git
    ```
5. Push to your repo, `tony`.
6. Create a new pull request.

**Comment by djw8605** [comment]
I'm going to close this request, since we have #17

**Pull request closed without merging**
